##
## Copyright (C) by Argonne National Laboratory
##     See COPYRIGHT in top-level directory
##

# -- THIS FILE IS AUTO-GENERATED -- 

mpi_sources += \
    src/binding/c/attr/attr_delete.c \
    src/binding/c/attr/attr_get.c \
    src/binding/c/attr/attr_put.c \
    src/binding/c/attr/comm_create_keyval.c \
    src/binding/c/attr/comm_delete_attr.c \
    src/binding/c/attr/comm_free_keyval.c \
    src/binding/c/attr/comm_get_attr.c \
    src/binding/c/attr/comm_set_attr.c \
    src/binding/c/attr/keyval_create.c \
    src/binding/c/attr/keyval_free.c \
    src/binding/c/attr/type_create_keyval.c \
    src/binding/c/attr/type_delete_attr.c \
    src/binding/c/attr/type_free_keyval.c \
    src/binding/c/attr/type_get_attr.c \
    src/binding/c/attr/type_set_attr.c \
    src/binding/c/attr/win_create_keyval.c \
    src/binding/c/attr/win_delete_attr.c \
    src/binding/c/attr/win_free_keyval.c \
    src/binding/c/attr/win_get_attr.c \
    src/binding/c/attr/win_set_attr.c \
    src/binding/c/coll/allgather.c \
    src/binding/c/coll/allgather_init.c \
    src/binding/c/coll/allgatherv.c \
    src/binding/c/coll/allgatherv_init.c \
    src/binding/c/coll/allreduce.c \
    src/binding/c/coll/allreduce_init.c \
    src/binding/c/coll/alltoall.c \
    src/binding/c/coll/alltoall_init.c \
    src/binding/c/coll/alltoallv.c \
    src/binding/c/coll/alltoallv_init.c \
    src/binding/c/coll/alltoallw.c \
    src/binding/c/coll/alltoallw_init.c \
    src/binding/c/coll/barrier.c \
    src/binding/c/coll/barrier_init.c \
    src/binding/c/coll/bcast.c \
    src/binding/c/coll/bcast_init.c \
    src/binding/c/coll/exscan.c \
    src/binding/c/coll/exscan_init.c \
    src/binding/c/coll/gather.c \
    src/binding/c/coll/gather_init.c \
    src/binding/c/coll/gatherv.c \
    src/binding/c/coll/gatherv_init.c \
    src/binding/c/coll/iallgather.c \
    src/binding/c/coll/iallgatherv.c \
    src/binding/c/coll/iallreduce.c \
    src/binding/c/coll/ialltoall.c \
    src/binding/c/coll/ialltoallv.c \
    src/binding/c/coll/ialltoallw.c \
    src/binding/c/coll/ibarrier.c \
    src/binding/c/coll/ibcast.c \
    src/binding/c/coll/iexscan.c \
    src/binding/c/coll/igather.c \
    src/binding/c/coll/igatherv.c \
    src/binding/c/coll/ineighbor_allgather.c \
    src/binding/c/coll/ineighbor_allgatherv.c \
    src/binding/c/coll/ineighbor_alltoall.c \
    src/binding/c/coll/ineighbor_alltoallv.c \
    src/binding/c/coll/ineighbor_alltoallw.c \
    src/binding/c/coll/ireduce.c \
    src/binding/c/coll/ireduce_scatter.c \
    src/binding/c/coll/ireduce_scatter_block.c \
    src/binding/c/coll/iscan.c \
    src/binding/c/coll/iscatter.c \
    src/binding/c/coll/iscatterv.c \
    src/binding/c/coll/neighbor_allgather.c \
    src/binding/c/coll/neighbor_allgather_init.c \
    src/binding/c/coll/neighbor_allgatherv.c \
    src/binding/c/coll/neighbor_allgatherv_init.c \
    src/binding/c/coll/neighbor_alltoall.c \
    src/binding/c/coll/neighbor_alltoall_init.c \
    src/binding/c/coll/neighbor_alltoallv.c \
    src/binding/c/coll/neighbor_alltoallv_init.c \
    src/binding/c/coll/neighbor_alltoallw.c \
    src/binding/c/coll/neighbor_alltoallw_init.c \
    src/binding/c/coll/reduce.c \
    src/binding/c/coll/reduce_init.c \
    src/binding/c/coll/reduce_local.c \
    src/binding/c/coll/reduce_scatter.c \
    src/binding/c/coll/reduce_scatter_block.c \
    src/binding/c/coll/reduce_scatter_block_init.c \
    src/binding/c/coll/reduce_scatter_init.c \
    src/binding/c/coll/scan.c \
    src/binding/c/coll/scan_init.c \
    src/binding/c/coll/scatter.c \
    src/binding/c/coll/scatter_init.c \
    src/binding/c/coll/scatterv.c \
    src/binding/c/coll/scatterv_init.c \
    src/binding/c/comm/comm_compare.c \
    src/binding/c/comm/comm_create.c \
    src/binding/c/comm/comm_create_group.c \
    src/binding/c/comm/comm_dup.c \
    src/binding/c/comm/comm_dup_with_info.c \
    src/binding/c/comm/comm_free.c \
    src/binding/c/comm/comm_get_info.c \
    src/binding/c/comm/comm_get_name.c \
    src/binding/c/comm/comm_group.c \
    src/binding/c/comm/comm_idup.c \
    src/binding/c/comm/comm_idup_with_info.c \
    src/binding/c/comm/comm_rank.c \
    src/binding/c/comm/comm_remote_group.c \
    src/binding/c/comm/comm_remote_size.c \
    src/binding/c/comm/comm_set_info.c \
    src/binding/c/comm/comm_set_name.c \
    src/binding/c/comm/comm_size.c \
    src/binding/c/comm/comm_split.c \
    src/binding/c/comm/comm_split_type.c \
    src/binding/c/comm/comm_test_inter.c \
    src/binding/c/comm/intercomm_create.c \
    src/binding/c/comm/intercomm_create_from_groups.c \
    src/binding/c/comm/intercomm_merge.c \
    src/binding/c/comm/comm_revoke.c \
    src/binding/c/comm/comm_shrink.c \
    src/binding/c/comm/comm_failure_ack.c \
    src/binding/c/comm/comm_failure_get_acked.c \
    src/binding/c/comm/comm_agree.c \
    src/binding/c/comm/comm_get_failed.c \
    src/binding/c/datatype/get_address.c \
    src/binding/c/datatype/get_count.c \
    src/binding/c/datatype/get_elements.c \
    src/binding/c/datatype/get_elements_x.c \
    src/binding/c/datatype/pack.c \
    src/binding/c/datatype/pack_external.c \
    src/binding/c/datatype/pack_external_size.c \
    src/binding/c/datatype/pack_size.c \
    src/binding/c/datatype/status_set_elements.c \
    src/binding/c/datatype/status_set_elements_x.c \
    src/binding/c/datatype/type_commit.c \
    src/binding/c/datatype/type_contiguous.c \
    src/binding/c/datatype/type_create_darray.c \
    src/binding/c/datatype/type_create_hindexed.c \
    src/binding/c/datatype/type_create_hindexed_block.c \
    src/binding/c/datatype/type_create_hvector.c \
    src/binding/c/datatype/type_create_indexed_block.c \
    src/binding/c/datatype/type_create_resized.c \
    src/binding/c/datatype/type_create_struct.c \
    src/binding/c/datatype/type_create_subarray.c \
    src/binding/c/datatype/type_dup.c \
    src/binding/c/datatype/type_free.c \
    src/binding/c/datatype/type_get_contents.c \
    src/binding/c/datatype/type_get_envelope.c \
    src/binding/c/datatype/type_get_extent.c \
    src/binding/c/datatype/type_get_extent_x.c \
    src/binding/c/datatype/type_get_name.c \
    src/binding/c/datatype/type_get_true_extent.c \
    src/binding/c/datatype/type_get_true_extent_x.c \
    src/binding/c/datatype/type_indexed.c \
    src/binding/c/datatype/type_match_size.c \
    src/binding/c/datatype/type_set_name.c \
    src/binding/c/datatype/type_size.c \
    src/binding/c/datatype/type_size_x.c \
    src/binding/c/datatype/type_vector.c \
    src/binding/c/datatype/unpack.c \
    src/binding/c/datatype/unpack_external.c \
    src/binding/c/datatype/address.c \
    src/binding/c/datatype/type_extent.c \
    src/binding/c/datatype/type_lb.c \
    src/binding/c/datatype/type_ub.c \
    src/binding/c/datatype/type_hindexed.c \
    src/binding/c/datatype/type_hvector.c \
    src/binding/c/datatype/type_struct.c \
    src/binding/c/datatype/type_iov_len.c \
    src/binding/c/datatype/type_iov.c \
    src/binding/c/errhan/add_error_class.c \
    src/binding/c/errhan/add_error_code.c \
    src/binding/c/errhan/add_error_string.c \
    src/binding/c/errhan/comm_call_errhandler.c \
    src/binding/c/errhan/comm_create_errhandler.c \
    src/binding/c/errhan/comm_get_errhandler.c \
    src/binding/c/errhan/comm_set_errhandler.c \
    src/binding/c/errhan/errhandler_free.c \
    src/binding/c/errhan/error_class.c \
    src/binding/c/errhan/error_string.c \
    src/binding/c/errhan/file_call_errhandler.c \
    src/binding/c/errhan/file_create_errhandler.c \
    src/binding/c/errhan/file_get_errhandler.c \
    src/binding/c/errhan/file_set_errhandler.c \
    src/binding/c/errhan/session_call_errhandler.c \
    src/binding/c/errhan/session_create_errhandler.c \
    src/binding/c/errhan/session_get_errhandler.c \
    src/binding/c/errhan/session_set_errhandler.c \
    src/binding/c/errhan/win_call_errhandler.c \
    src/binding/c/errhan/win_create_errhandler.c \
    src/binding/c/errhan/win_get_errhandler.c \
    src/binding/c/errhan/win_set_errhandler.c \
    src/binding/c/errhan/delete_error_class.c \
    src/binding/c/errhan/delete_error_code.c \
    src/binding/c/errhan/delete_error_string.c \
    src/binding/c/errhan/errhandler_create.c \
    src/binding/c/errhan/errhandler_get.c \
    src/binding/c/errhan/errhandler_set.c \
    src/binding/c/group/group_compare.c \
    src/binding/c/group/group_difference.c \
    src/binding/c/group/group_excl.c \
    src/binding/c/group/group_free.c \
    src/binding/c/group/group_incl.c \
    src/binding/c/group/group_intersection.c \
    src/binding/c/group/group_range_excl.c \
    src/binding/c/group/group_range_incl.c \
    src/binding/c/group/group_rank.c \
    src/binding/c/group/group_size.c \
    src/binding/c/group/group_translate_ranks.c \
    src/binding/c/group/group_union.c \
    src/binding/c/info/info_create.c \
    src/binding/c/info/info_create_env.c \
    src/binding/c/info/info_delete.c \
    src/binding/c/info/info_dup.c \
    src/binding/c/info/info_free.c \
    src/binding/c/info/info_get.c \
    src/binding/c/info/info_get_nkeys.c \
    src/binding/c/info/info_get_nthkey.c \
    src/binding/c/info/info_get_string.c \
    src/binding/c/info/info_get_valuelen.c \
    src/binding/c/info/info_set.c \
    src/binding/c/info/info_set_hex.c \
    src/binding/c/init/abort.c \
    src/binding/c/init/comm_create_from_group.c \
    src/binding/c/init/finalize.c \
    src/binding/c/init/finalized.c \
    src/binding/c/init/group_from_session_pset.c \
    src/binding/c/init/init.c \
    src/binding/c/init/init_thread.c \
    src/binding/c/init/initialized.c \
    src/binding/c/init/is_thread_main.c \
    src/binding/c/init/query_thread.c \
    src/binding/c/init/session_finalize.c \
    src/binding/c/init/session_get_info.c \
    src/binding/c/init/session_get_nth_pset.c \
    src/binding/c/init/session_get_num_psets.c \
    src/binding/c/init/session_get_pset_info.c \
    src/binding/c/init/session_init.c \
    src/binding/c/misc/aint_add.c \
    src/binding/c/misc/aint_diff.c \
    src/binding/c/misc/get_library_version.c \
    src/binding/c/misc/get_processor_name.c \
    src/binding/c/misc/get_version.c \
    src/binding/c/misc/pcontrol.c \
    src/binding/c/misc/gpu_query_support.c \
    src/binding/c/misc/query_cuda_support.c \
    src/binding/c/misc/query_ze_support.c \
    src/binding/c/misc/query_hip_support.c \
    src/binding/c/mpit/category_changed.c \
    src/binding/c/mpit/category_get_categories.c \
    src/binding/c/mpit/category_get_cvars.c \
    src/binding/c/mpit/category_get_events.c \
    src/binding/c/mpit/category_get_index.c \
    src/binding/c/mpit/category_get_info.c \
    src/binding/c/mpit/category_get_num.c \
    src/binding/c/mpit/category_get_num_events.c \
    src/binding/c/mpit/category_get_pvars.c \
    src/binding/c/mpit/cvar_get_index.c \
    src/binding/c/mpit/cvar_get_info.c \
    src/binding/c/mpit/cvar_get_num.c \
    src/binding/c/mpit/cvar_handle_alloc.c \
    src/binding/c/mpit/cvar_handle_free.c \
    src/binding/c/mpit/cvar_read.c \
    src/binding/c/mpit/cvar_write.c \
    src/binding/c/mpit/enum_get_info.c \
    src/binding/c/mpit/enum_get_item.c \
    src/binding/c/mpit/event_callback_get_info.c \
    src/binding/c/mpit/event_callback_set_info.c \
    src/binding/c/mpit/event_copy.c \
    src/binding/c/mpit/event_get_index.c \
    src/binding/c/mpit/event_get_info.c \
    src/binding/c/mpit/event_get_num.c \
    src/binding/c/mpit/event_get_source.c \
    src/binding/c/mpit/event_get_timestamp.c \
    src/binding/c/mpit/event_handle_alloc.c \
    src/binding/c/mpit/event_handle_free.c \
    src/binding/c/mpit/event_handle_get_info.c \
    src/binding/c/mpit/event_handle_set_info.c \
    src/binding/c/mpit/event_read.c \
    src/binding/c/mpit/event_register_callback.c \
    src/binding/c/mpit/event_set_dropped_handler.c \
    src/binding/c/mpit/finalize.c \
    src/binding/c/mpit/init_thread.c \
    src/binding/c/mpit/pvar_get_index.c \
    src/binding/c/mpit/pvar_get_info.c \
    src/binding/c/mpit/pvar_get_num.c \
    src/binding/c/mpit/pvar_handle_alloc.c \
    src/binding/c/mpit/pvar_handle_free.c \
    src/binding/c/mpit/pvar_read.c \
    src/binding/c/mpit/pvar_readreset.c \
    src/binding/c/mpit/pvar_reset.c \
    src/binding/c/mpit/pvar_session_create.c \
    src/binding/c/mpit/pvar_session_free.c \
    src/binding/c/mpit/pvar_start.c \
    src/binding/c/mpit/pvar_stop.c \
    src/binding/c/mpit/pvar_write.c \
    src/binding/c/mpit/source_get_info.c \
    src/binding/c/mpit/source_get_num.c \
    src/binding/c/mpit/source_get_timestamp.c \
    src/binding/c/op/op_commutative.c \
    src/binding/c/op/op_create.c \
    src/binding/c/op/op_free.c \
    src/binding/c/part/parrived.c \
    src/binding/c/part/pready.c \
    src/binding/c/part/pready_list.c \
    src/binding/c/part/pready_range.c \
    src/binding/c/part/precv_init.c \
    src/binding/c/part/psend_init.c \
    src/binding/c/pt2pt/bsend.c \
    src/binding/c/pt2pt/bsend_init.c \
    src/binding/c/pt2pt/buffer_attach.c \
    src/binding/c/pt2pt/buffer_detach.c \
    src/binding/c/pt2pt/ibsend.c \
    src/binding/c/pt2pt/improbe.c \
    src/binding/c/pt2pt/imrecv.c \
    src/binding/c/pt2pt/iprobe.c \
    src/binding/c/pt2pt/irecv.c \
    src/binding/c/pt2pt/irsend.c \
    src/binding/c/pt2pt/isend.c \
    src/binding/c/pt2pt/isendrecv.c \
    src/binding/c/pt2pt/isendrecv_replace.c \
    src/binding/c/pt2pt/issend.c \
    src/binding/c/pt2pt/mprobe.c \
    src/binding/c/pt2pt/mrecv.c \
    src/binding/c/pt2pt/probe.c \
    src/binding/c/pt2pt/recv.c \
    src/binding/c/pt2pt/recv_init.c \
    src/binding/c/pt2pt/rsend.c \
    src/binding/c/pt2pt/rsend_init.c \
    src/binding/c/pt2pt/send.c \
    src/binding/c/pt2pt/send_init.c \
    src/binding/c/pt2pt/sendrecv.c \
    src/binding/c/pt2pt/sendrecv_replace.c \
    src/binding/c/pt2pt/ssend.c \
    src/binding/c/pt2pt/ssend_init.c \
    src/binding/c/request/cancel.c \
    src/binding/c/request/grequest_complete.c \
    src/binding/c/request/grequest_start.c \
    src/binding/c/request/request_free.c \
    src/binding/c/request/request_get_status.c \
    src/binding/c/request/start.c \
    src/binding/c/request/startall.c \
    src/binding/c/request/status_set_cancelled.c \
    src/binding/c/request/test.c \
    src/binding/c/request/test_cancelled.c \
    src/binding/c/request/testall.c \
    src/binding/c/request/testany.c \
    src/binding/c/request/testsome.c \
    src/binding/c/request/wait.c \
    src/binding/c/request/waitall.c \
    src/binding/c/request/waitany.c \
    src/binding/c/request/waitsome.c \
    src/binding/c/request/grequest_start_x.c \
    src/binding/c/request/grequest_class_create.c \
    src/binding/c/request/grequest_class_allocate.c \
    src/binding/c/rma/accumulate.c \
    src/binding/c/rma/alloc_mem.c \
    src/binding/c/rma/compare_and_swap.c \
    src/binding/c/rma/fetch_and_op.c \
    src/binding/c/rma/free_mem.c \
    src/binding/c/rma/get.c \
    src/binding/c/rma/get_accumulate.c \
    src/binding/c/rma/put.c \
    src/binding/c/rma/raccumulate.c \
    src/binding/c/rma/rget.c \
    src/binding/c/rma/rget_accumulate.c \
    src/binding/c/rma/rput.c \
    src/binding/c/rma/win_allocate.c \
    src/binding/c/rma/win_allocate_shared.c \
    src/binding/c/rma/win_attach.c \
    src/binding/c/rma/win_complete.c \
    src/binding/c/rma/win_create.c \
    src/binding/c/rma/win_create_dynamic.c \
    src/binding/c/rma/win_detach.c \
    src/binding/c/rma/win_fence.c \
    src/binding/c/rma/win_flush.c \
    src/binding/c/rma/win_flush_all.c \
    src/binding/c/rma/win_flush_local.c \
    src/binding/c/rma/win_flush_local_all.c \
    src/binding/c/rma/win_free.c \
    src/binding/c/rma/win_get_group.c \
    src/binding/c/rma/win_get_info.c \
    src/binding/c/rma/win_get_name.c \
    src/binding/c/rma/win_lock.c \
    src/binding/c/rma/win_lock_all.c \
    src/binding/c/rma/win_post.c \
    src/binding/c/rma/win_set_info.c \
    src/binding/c/rma/win_set_name.c \
    src/binding/c/rma/win_shared_query.c \
    src/binding/c/rma/win_start.c \
    src/binding/c/rma/win_sync.c \
    src/binding/c/rma/win_test.c \
    src/binding/c/rma/win_unlock.c \
    src/binding/c/rma/win_unlock_all.c \
    src/binding/c/rma/win_wait.c \
    src/binding/c/spawn/close_port.c \
    src/binding/c/spawn/comm_accept.c \
    src/binding/c/spawn/comm_connect.c \
    src/binding/c/spawn/comm_disconnect.c \
    src/binding/c/spawn/comm_get_parent.c \
    src/binding/c/spawn/comm_join.c \
    src/binding/c/spawn/comm_spawn.c \
    src/binding/c/spawn/comm_spawn_multiple.c \
    src/binding/c/spawn/lookup_name.c \
    src/binding/c/spawn/open_port.c \
    src/binding/c/spawn/publish_name.c \
    src/binding/c/spawn/unpublish_name.c \
    src/binding/c/stream/stream_create.c \
    src/binding/c/stream/stream_free.c \
    src/binding/c/stream/stream_comm_create.c \
    src/binding/c/stream/stream_comm_create_multiplex.c \
    src/binding/c/stream/comm_get_stream.c \
    src/binding/c/stream/stream_progress.c \
    src/binding/c/stream/start_progress_thread.c \
    src/binding/c/stream/stop_progress_thread.c \
    src/binding/c/stream/stream_send.c \
    src/binding/c/stream/stream_isend.c \
    src/binding/c/stream/stream_recv.c \
    src/binding/c/stream/stream_irecv.c \
    src/binding/c/stream/send_enqueue.c \
    src/binding/c/stream/recv_enqueue.c \
    src/binding/c/stream/isend_enqueue.c \
    src/binding/c/stream/irecv_enqueue.c \
    src/binding/c/stream/wait_enqueue.c \
    src/binding/c/stream/waitall_enqueue.c \
    src/binding/c/stream/allreduce_enqueue.c \
    src/binding/c/timer/wtick.c \
    src/binding/c/timer/wtime.c \
    src/binding/c/topo/cart_coords.c \
    src/binding/c/topo/cart_create.c \
    src/binding/c/topo/cart_get.c \
    src/binding/c/topo/cart_map.c \
    src/binding/c/topo/cart_rank.c \
    src/binding/c/topo/cart_shift.c \
    src/binding/c/topo/cart_sub.c \
    src/binding/c/topo/cartdim_get.c \
    src/binding/c/topo/dims_create.c \
    src/binding/c/topo/dist_graph_create.c \
    src/binding/c/topo/dist_graph_create_adjacent.c \
    src/binding/c/topo/dist_graph_neighbors.c \
    src/binding/c/topo/dist_graph_neighbors_count.c \
    src/binding/c/topo/graph_create.c \
    src/binding/c/topo/graph_get.c \
    src/binding/c/topo/graph_map.c \
    src/binding/c/topo/graph_neighbors.c \
    src/binding/c/topo/graph_neighbors_count.c \
    src/binding/c/topo/graphdims_get.c \
    src/binding/c/topo/topo_test.c
doc3_src_txt += \
    src/binding/c/mansrc/attr_delete.txt \
    src/binding/c/mansrc/attr_get.txt \
    src/binding/c/mansrc/attr_put.txt \
    src/binding/c/mansrc/comm_create_keyval.txt \
    src/binding/c/mansrc/comm_delete_attr.txt \
    src/binding/c/mansrc/comm_free_keyval.txt \
    src/binding/c/mansrc/comm_get_attr.txt \
    src/binding/c/mansrc/comm_set_attr.txt \
    src/binding/c/mansrc/keyval_create.txt \
    src/binding/c/mansrc/keyval_free.txt \
    src/binding/c/mansrc/type_create_keyval.txt \
    src/binding/c/mansrc/type_delete_attr.txt \
    src/binding/c/mansrc/type_free_keyval.txt \
    src/binding/c/mansrc/type_get_attr.txt \
    src/binding/c/mansrc/type_set_attr.txt \
    src/binding/c/mansrc/win_create_keyval.txt \
    src/binding/c/mansrc/win_delete_attr.txt \
    src/binding/c/mansrc/win_free_keyval.txt \
    src/binding/c/mansrc/win_get_attr.txt \
    src/binding/c/mansrc/win_set_attr.txt \
    src/binding/c/mansrc/allgather.txt \
    src/binding/c/mansrc/allgather_init.txt \
    src/binding/c/mansrc/allgatherv.txt \
    src/binding/c/mansrc/allgatherv_init.txt \
    src/binding/c/mansrc/allreduce.txt \
    src/binding/c/mansrc/allreduce_init.txt \
    src/binding/c/mansrc/alltoall.txt \
    src/binding/c/mansrc/alltoall_init.txt \
    src/binding/c/mansrc/alltoallv.txt \
    src/binding/c/mansrc/alltoallv_init.txt \
    src/binding/c/mansrc/alltoallw.txt \
    src/binding/c/mansrc/alltoallw_init.txt \
    src/binding/c/mansrc/barrier.txt \
    src/binding/c/mansrc/barrier_init.txt \
    src/binding/c/mansrc/bcast.txt \
    src/binding/c/mansrc/bcast_init.txt \
    src/binding/c/mansrc/exscan.txt \
    src/binding/c/mansrc/exscan_init.txt \
    src/binding/c/mansrc/gather.txt \
    src/binding/c/mansrc/gather_init.txt \
    src/binding/c/mansrc/gatherv.txt \
    src/binding/c/mansrc/gatherv_init.txt \
    src/binding/c/mansrc/iallgather.txt \
    src/binding/c/mansrc/iallgatherv.txt \
    src/binding/c/mansrc/iallreduce.txt \
    src/binding/c/mansrc/ialltoall.txt \
    src/binding/c/mansrc/ialltoallv.txt \
    src/binding/c/mansrc/ialltoallw.txt \
    src/binding/c/mansrc/ibarrier.txt \
    src/binding/c/mansrc/ibcast.txt \
    src/binding/c/mansrc/iexscan.txt \
    src/binding/c/mansrc/igather.txt \
    src/binding/c/mansrc/igatherv.txt \
    src/binding/c/mansrc/ineighbor_allgather.txt \
    src/binding/c/mansrc/ineighbor_allgatherv.txt \
    src/binding/c/mansrc/ineighbor_alltoall.txt \
    src/binding/c/mansrc/ineighbor_alltoallv.txt \
    src/binding/c/mansrc/ineighbor_alltoallw.txt \
    src/binding/c/mansrc/ireduce.txt \
    src/binding/c/mansrc/ireduce_scatter.txt \
    src/binding/c/mansrc/ireduce_scatter_block.txt \
    src/binding/c/mansrc/iscan.txt \
    src/binding/c/mansrc/iscatter.txt \
    src/binding/c/mansrc/iscatterv.txt \
    src/binding/c/mansrc/neighbor_allgather.txt \
    src/binding/c/mansrc/neighbor_allgather_init.txt \
    src/binding/c/mansrc/neighbor_allgatherv.txt \
    src/binding/c/mansrc/neighbor_allgatherv_init.txt \
    src/binding/c/mansrc/neighbor_alltoall.txt \
    src/binding/c/mansrc/neighbor_alltoall_init.txt \
    src/binding/c/mansrc/neighbor_alltoallv.txt \
    src/binding/c/mansrc/neighbor_alltoallv_init.txt \
    src/binding/c/mansrc/neighbor_alltoallw.txt \
    src/binding/c/mansrc/neighbor_alltoallw_init.txt \
    src/binding/c/mansrc/reduce.txt \
    src/binding/c/mansrc/reduce_init.txt \
    src/binding/c/mansrc/reduce_local.txt \
    src/binding/c/mansrc/reduce_scatter.txt \
    src/binding/c/mansrc/reduce_scatter_block.txt \
    src/binding/c/mansrc/reduce_scatter_block_init.txt \
    src/binding/c/mansrc/reduce_scatter_init.txt \
    src/binding/c/mansrc/scan.txt \
    src/binding/c/mansrc/scan_init.txt \
    src/binding/c/mansrc/scatter.txt \
    src/binding/c/mansrc/scatter_init.txt \
    src/binding/c/mansrc/scatterv.txt \
    src/binding/c/mansrc/scatterv_init.txt \
    src/binding/c/mansrc/comm_compare.txt \
    src/binding/c/mansrc/comm_create.txt \
    src/binding/c/mansrc/comm_create_group.txt \
    src/binding/c/mansrc/comm_dup.txt \
    src/binding/c/mansrc/comm_dup_with_info.txt \
    src/binding/c/mansrc/comm_free.txt \
    src/binding/c/mansrc/comm_get_info.txt \
    src/binding/c/mansrc/comm_get_name.txt \
    src/binding/c/mansrc/comm_group.txt \
    src/binding/c/mansrc/comm_idup.txt \
    src/binding/c/mansrc/comm_idup_with_info.txt \
    src/binding/c/mansrc/comm_rank.txt \
    src/binding/c/mansrc/comm_remote_group.txt \
    src/binding/c/mansrc/comm_remote_size.txt \
    src/binding/c/mansrc/comm_set_info.txt \
    src/binding/c/mansrc/comm_set_name.txt \
    src/binding/c/mansrc/comm_size.txt \
    src/binding/c/mansrc/comm_split.txt \
    src/binding/c/mansrc/comm_split_type.txt \
    src/binding/c/mansrc/comm_test_inter.txt \
    src/binding/c/mansrc/intercomm_create.txt \
    src/binding/c/mansrc/intercomm_create_from_groups.txt \
    src/binding/c/mansrc/intercomm_merge.txt \
    src/binding/c/mansrc/comm_revoke.txt \
    src/binding/c/mansrc/comm_shrink.txt \
    src/binding/c/mansrc/comm_failure_ack.txt \
    src/binding/c/mansrc/comm_failure_get_acked.txt \
    src/binding/c/mansrc/comm_agree.txt \
    src/binding/c/mansrc/comm_get_failed.txt \
    src/binding/c/mansrc/get_address.txt \
    src/binding/c/mansrc/get_count.txt \
    src/binding/c/mansrc/get_elements.txt \
    src/binding/c/mansrc/get_elements_x.txt \
    src/binding/c/mansrc/pack.txt \
    src/binding/c/mansrc/pack_external.txt \
    src/binding/c/mansrc/pack_external_size.txt \
    src/binding/c/mansrc/pack_size.txt \
    src/binding/c/mansrc/status_set_elements.txt \
    src/binding/c/mansrc/status_set_elements_x.txt \
    src/binding/c/mansrc/type_commit.txt \
    src/binding/c/mansrc/type_contiguous.txt \
    src/binding/c/mansrc/type_create_darray.txt \
    src/binding/c/mansrc/type_create_hindexed.txt \
    src/binding/c/mansrc/type_create_hindexed_block.txt \
    src/binding/c/mansrc/type_create_hvector.txt \
    src/binding/c/mansrc/type_create_indexed_block.txt \
    src/binding/c/mansrc/type_create_resized.txt \
    src/binding/c/mansrc/type_create_struct.txt \
    src/binding/c/mansrc/type_create_subarray.txt \
    src/binding/c/mansrc/type_dup.txt \
    src/binding/c/mansrc/type_free.txt \
    src/binding/c/mansrc/type_get_contents.txt \
    src/binding/c/mansrc/type_get_envelope.txt \
    src/binding/c/mansrc/type_get_extent.txt \
    src/binding/c/mansrc/type_get_extent_x.txt \
    src/binding/c/mansrc/type_get_name.txt \
    src/binding/c/mansrc/type_get_true_extent.txt \
    src/binding/c/mansrc/type_get_true_extent_x.txt \
    src/binding/c/mansrc/type_indexed.txt \
    src/binding/c/mansrc/type_match_size.txt \
    src/binding/c/mansrc/type_set_name.txt \
    src/binding/c/mansrc/type_size.txt \
    src/binding/c/mansrc/type_size_x.txt \
    src/binding/c/mansrc/type_vector.txt \
    src/binding/c/mansrc/unpack.txt \
    src/binding/c/mansrc/unpack_external.txt \
    src/binding/c/mansrc/address.txt \
    src/binding/c/mansrc/type_extent.txt \
    src/binding/c/mansrc/type_lb.txt \
    src/binding/c/mansrc/type_ub.txt \
    src/binding/c/mansrc/type_hindexed.txt \
    src/binding/c/mansrc/type_hvector.txt \
    src/binding/c/mansrc/type_struct.txt \
    src/binding/c/mansrc/type_iov_len.txt \
    src/binding/c/mansrc/type_iov.txt \
    src/binding/c/mansrc/add_error_class.txt \
    src/binding/c/mansrc/add_error_code.txt \
    src/binding/c/mansrc/add_error_string.txt \
    src/binding/c/mansrc/comm_call_errhandler.txt \
    src/binding/c/mansrc/comm_create_errhandler.txt \
    src/binding/c/mansrc/comm_get_errhandler.txt \
    src/binding/c/mansrc/comm_set_errhandler.txt \
    src/binding/c/mansrc/errhandler_free.txt \
    src/binding/c/mansrc/error_class.txt \
    src/binding/c/mansrc/error_string.txt \
    src/binding/c/mansrc/file_call_errhandler.txt \
    src/binding/c/mansrc/file_create_errhandler.txt \
    src/binding/c/mansrc/file_get_errhandler.txt \
    src/binding/c/mansrc/file_set_errhandler.txt \
    src/binding/c/mansrc/session_call_errhandler.txt \
    src/binding/c/mansrc/session_create_errhandler.txt \
    src/binding/c/mansrc/session_get_errhandler.txt \
    src/binding/c/mansrc/session_set_errhandler.txt \
    src/binding/c/mansrc/win_call_errhandler.txt \
    src/binding/c/mansrc/win_create_errhandler.txt \
    src/binding/c/mansrc/win_get_errhandler.txt \
    src/binding/c/mansrc/win_set_errhandler.txt \
    src/binding/c/mansrc/delete_error_class.txt \
    src/binding/c/mansrc/delete_error_code.txt \
    src/binding/c/mansrc/delete_error_string.txt \
    src/binding/c/mansrc/errhandler_create.txt \
    src/binding/c/mansrc/errhandler_get.txt \
    src/binding/c/mansrc/errhandler_set.txt \
    src/binding/c/mansrc/group_compare.txt \
    src/binding/c/mansrc/group_difference.txt \
    src/binding/c/mansrc/group_excl.txt \
    src/binding/c/mansrc/group_free.txt \
    src/binding/c/mansrc/group_incl.txt \
    src/binding/c/mansrc/group_intersection.txt \
    src/binding/c/mansrc/group_range_excl.txt \
    src/binding/c/mansrc/group_range_incl.txt \
    src/binding/c/mansrc/group_rank.txt \
    src/binding/c/mansrc/group_size.txt \
    src/binding/c/mansrc/group_translate_ranks.txt \
    src/binding/c/mansrc/group_union.txt \
    src/binding/c/mansrc/info_create.txt \
    src/binding/c/mansrc/info_create_env.txt \
    src/binding/c/mansrc/info_delete.txt \
    src/binding/c/mansrc/info_dup.txt \
    src/binding/c/mansrc/info_free.txt \
    src/binding/c/mansrc/info_get.txt \
    src/binding/c/mansrc/info_get_nkeys.txt \
    src/binding/c/mansrc/info_get_nthkey.txt \
    src/binding/c/mansrc/info_get_string.txt \
    src/binding/c/mansrc/info_get_valuelen.txt \
    src/binding/c/mansrc/info_set.txt \
    src/binding/c/mansrc/info_set_hex.txt \
    src/binding/c/mansrc/abort.txt \
    src/binding/c/mansrc/comm_create_from_group.txt \
    src/binding/c/mansrc/finalize.txt \
    src/binding/c/mansrc/finalized.txt \
    src/binding/c/mansrc/group_from_session_pset.txt \
    src/binding/c/mansrc/init.txt \
    src/binding/c/mansrc/init_thread.txt \
    src/binding/c/mansrc/initialized.txt \
    src/binding/c/mansrc/is_thread_main.txt \
    src/binding/c/mansrc/query_thread.txt \
    src/binding/c/mansrc/session_finalize.txt \
    src/binding/c/mansrc/session_get_info.txt \
    src/binding/c/mansrc/session_get_nth_pset.txt \
    src/binding/c/mansrc/session_get_num_psets.txt \
    src/binding/c/mansrc/session_get_pset_info.txt \
    src/binding/c/mansrc/session_init.txt \
    src/binding/c/mansrc/aint_add.txt \
    src/binding/c/mansrc/aint_diff.txt \
    src/binding/c/mansrc/get_library_version.txt \
    src/binding/c/mansrc/get_processor_name.txt \
    src/binding/c/mansrc/get_version.txt \
    src/binding/c/mansrc/pcontrol.txt \
    src/binding/c/mansrc/gpu_query_support.txt \
    src/binding/c/mansrc/query_cuda_support.txt \
    src/binding/c/mansrc/query_ze_support.txt \
    src/binding/c/mansrc/query_hip_support.txt \
    src/binding/c/mansrc/category_changed.txt \
    src/binding/c/mansrc/category_get_categories.txt \
    src/binding/c/mansrc/category_get_cvars.txt \
    src/binding/c/mansrc/category_get_events.txt \
    src/binding/c/mansrc/category_get_index.txt \
    src/binding/c/mansrc/category_get_info.txt \
    src/binding/c/mansrc/category_get_num.txt \
    src/binding/c/mansrc/category_get_num_events.txt \
    src/binding/c/mansrc/category_get_pvars.txt \
    src/binding/c/mansrc/cvar_get_index.txt \
    src/binding/c/mansrc/cvar_get_info.txt \
    src/binding/c/mansrc/cvar_get_num.txt \
    src/binding/c/mansrc/cvar_handle_alloc.txt \
    src/binding/c/mansrc/cvar_handle_free.txt \
    src/binding/c/mansrc/cvar_read.txt \
    src/binding/c/mansrc/cvar_write.txt \
    src/binding/c/mansrc/enum_get_info.txt \
    src/binding/c/mansrc/enum_get_item.txt \
    src/binding/c/mansrc/event_callback_get_info.txt \
    src/binding/c/mansrc/event_callback_set_info.txt \
    src/binding/c/mansrc/event_copy.txt \
    src/binding/c/mansrc/event_get_index.txt \
    src/binding/c/mansrc/event_get_info.txt \
    src/binding/c/mansrc/event_get_num.txt \
    src/binding/c/mansrc/event_get_source.txt \
    src/binding/c/mansrc/event_get_timestamp.txt \
    src/binding/c/mansrc/event_handle_alloc.txt \
    src/binding/c/mansrc/event_handle_free.txt \
    src/binding/c/mansrc/event_handle_get_info.txt \
    src/binding/c/mansrc/event_handle_set_info.txt \
    src/binding/c/mansrc/event_read.txt \
    src/binding/c/mansrc/event_register_callback.txt \
    src/binding/c/mansrc/event_set_dropped_handler.txt \
    src/binding/c/mansrc/finalize.txt \
    src/binding/c/mansrc/init_thread.txt \
    src/binding/c/mansrc/pvar_get_index.txt \
    src/binding/c/mansrc/pvar_get_info.txt \
    src/binding/c/mansrc/pvar_get_num.txt \
    src/binding/c/mansrc/pvar_handle_alloc.txt \
    src/binding/c/mansrc/pvar_handle_free.txt \
    src/binding/c/mansrc/pvar_read.txt \
    src/binding/c/mansrc/pvar_readreset.txt \
    src/binding/c/mansrc/pvar_reset.txt \
    src/binding/c/mansrc/pvar_session_create.txt \
    src/binding/c/mansrc/pvar_session_free.txt \
    src/binding/c/mansrc/pvar_start.txt \
    src/binding/c/mansrc/pvar_stop.txt \
    src/binding/c/mansrc/pvar_write.txt \
    src/binding/c/mansrc/source_get_info.txt \
    src/binding/c/mansrc/source_get_num.txt \
    src/binding/c/mansrc/source_get_timestamp.txt \
    src/binding/c/mansrc/op_commutative.txt \
    src/binding/c/mansrc/op_create.txt \
    src/binding/c/mansrc/op_free.txt \
    src/binding/c/mansrc/parrived.txt \
    src/binding/c/mansrc/pready.txt \
    src/binding/c/mansrc/pready_list.txt \
    src/binding/c/mansrc/pready_range.txt \
    src/binding/c/mansrc/precv_init.txt \
    src/binding/c/mansrc/psend_init.txt \
    src/binding/c/mansrc/bsend.txt \
    src/binding/c/mansrc/bsend_init.txt \
    src/binding/c/mansrc/buffer_attach.txt \
    src/binding/c/mansrc/buffer_detach.txt \
    src/binding/c/mansrc/ibsend.txt \
    src/binding/c/mansrc/improbe.txt \
    src/binding/c/mansrc/imrecv.txt \
    src/binding/c/mansrc/iprobe.txt \
    src/binding/c/mansrc/irecv.txt \
    src/binding/c/mansrc/irsend.txt \
    src/binding/c/mansrc/isend.txt \
    src/binding/c/mansrc/isendrecv.txt \
    src/binding/c/mansrc/isendrecv_replace.txt \
    src/binding/c/mansrc/issend.txt \
    src/binding/c/mansrc/mprobe.txt \
    src/binding/c/mansrc/mrecv.txt \
    src/binding/c/mansrc/probe.txt \
    src/binding/c/mansrc/recv.txt \
    src/binding/c/mansrc/recv_init.txt \
    src/binding/c/mansrc/rsend.txt \
    src/binding/c/mansrc/rsend_init.txt \
    src/binding/c/mansrc/send.txt \
    src/binding/c/mansrc/send_init.txt \
    src/binding/c/mansrc/sendrecv.txt \
    src/binding/c/mansrc/sendrecv_replace.txt \
    src/binding/c/mansrc/ssend.txt \
    src/binding/c/mansrc/ssend_init.txt \
    src/binding/c/mansrc/cancel.txt \
    src/binding/c/mansrc/grequest_complete.txt \
    src/binding/c/mansrc/grequest_start.txt \
    src/binding/c/mansrc/request_free.txt \
    src/binding/c/mansrc/request_get_status.txt \
    src/binding/c/mansrc/start.txt \
    src/binding/c/mansrc/startall.txt \
    src/binding/c/mansrc/status_set_cancelled.txt \
    src/binding/c/mansrc/test.txt \
    src/binding/c/mansrc/test_cancelled.txt \
    src/binding/c/mansrc/testall.txt \
    src/binding/c/mansrc/testany.txt \
    src/binding/c/mansrc/testsome.txt \
    src/binding/c/mansrc/wait.txt \
    src/binding/c/mansrc/waitall.txt \
    src/binding/c/mansrc/waitany.txt \
    src/binding/c/mansrc/waitsome.txt \
    src/binding/c/mansrc/grequest_start_x.txt \
    src/binding/c/mansrc/grequest_class_create.txt \
    src/binding/c/mansrc/grequest_class_allocate.txt \
    src/binding/c/mansrc/accumulate.txt \
    src/binding/c/mansrc/alloc_mem.txt \
    src/binding/c/mansrc/compare_and_swap.txt \
    src/binding/c/mansrc/fetch_and_op.txt \
    src/binding/c/mansrc/free_mem.txt \
    src/binding/c/mansrc/get.txt \
    src/binding/c/mansrc/get_accumulate.txt \
    src/binding/c/mansrc/put.txt \
    src/binding/c/mansrc/raccumulate.txt \
    src/binding/c/mansrc/rget.txt \
    src/binding/c/mansrc/rget_accumulate.txt \
    src/binding/c/mansrc/rput.txt \
    src/binding/c/mansrc/win_allocate.txt \
    src/binding/c/mansrc/win_allocate_shared.txt \
    src/binding/c/mansrc/win_attach.txt \
    src/binding/c/mansrc/win_complete.txt \
    src/binding/c/mansrc/win_create.txt \
    src/binding/c/mansrc/win_create_dynamic.txt \
    src/binding/c/mansrc/win_detach.txt \
    src/binding/c/mansrc/win_fence.txt \
    src/binding/c/mansrc/win_flush.txt \
    src/binding/c/mansrc/win_flush_all.txt \
    src/binding/c/mansrc/win_flush_local.txt \
    src/binding/c/mansrc/win_flush_local_all.txt \
    src/binding/c/mansrc/win_free.txt \
    src/binding/c/mansrc/win_get_group.txt \
    src/binding/c/mansrc/win_get_info.txt \
    src/binding/c/mansrc/win_get_name.txt \
    src/binding/c/mansrc/win_lock.txt \
    src/binding/c/mansrc/win_lock_all.txt \
    src/binding/c/mansrc/win_post.txt \
    src/binding/c/mansrc/win_set_info.txt \
    src/binding/c/mansrc/win_set_name.txt \
    src/binding/c/mansrc/win_shared_query.txt \
    src/binding/c/mansrc/win_start.txt \
    src/binding/c/mansrc/win_sync.txt \
    src/binding/c/mansrc/win_test.txt \
    src/binding/c/mansrc/win_unlock.txt \
    src/binding/c/mansrc/win_unlock_all.txt \
    src/binding/c/mansrc/win_wait.txt \
    src/binding/c/mansrc/close_port.txt \
    src/binding/c/mansrc/comm_accept.txt \
    src/binding/c/mansrc/comm_connect.txt \
    src/binding/c/mansrc/comm_disconnect.txt \
    src/binding/c/mansrc/comm_get_parent.txt \
    src/binding/c/mansrc/comm_join.txt \
    src/binding/c/mansrc/comm_spawn.txt \
    src/binding/c/mansrc/comm_spawn_multiple.txt \
    src/binding/c/mansrc/lookup_name.txt \
    src/binding/c/mansrc/open_port.txt \
    src/binding/c/mansrc/publish_name.txt \
    src/binding/c/mansrc/unpublish_name.txt \
    src/binding/c/mansrc/stream_create.txt \
    src/binding/c/mansrc/stream_free.txt \
    src/binding/c/mansrc/stream_comm_create.txt \
    src/binding/c/mansrc/stream_comm_create_multiplex.txt \
    src/binding/c/mansrc/comm_get_stream.txt \
    src/binding/c/mansrc/stream_progress.txt \
    src/binding/c/mansrc/start_progress_thread.txt \
    src/binding/c/mansrc/stop_progress_thread.txt \
    src/binding/c/mansrc/stream_send.txt \
    src/binding/c/mansrc/stream_isend.txt \
    src/binding/c/mansrc/stream_recv.txt \
    src/binding/c/mansrc/stream_irecv.txt \
    src/binding/c/mansrc/send_enqueue.txt \
    src/binding/c/mansrc/recv_enqueue.txt \
    src/binding/c/mansrc/isend_enqueue.txt \
    src/binding/c/mansrc/irecv_enqueue.txt \
    src/binding/c/mansrc/wait_enqueue.txt \
    src/binding/c/mansrc/waitall_enqueue.txt \
    src/binding/c/mansrc/allreduce_enqueue.txt \
    src/binding/c/mansrc/wtick.txt \
    src/binding/c/mansrc/wtime.txt \
    src/binding/c/mansrc/cart_coords.txt \
    src/binding/c/mansrc/cart_create.txt \
    src/binding/c/mansrc/cart_get.txt \
    src/binding/c/mansrc/cart_map.txt \
    src/binding/c/mansrc/cart_rank.txt \
    src/binding/c/mansrc/cart_shift.txt \
    src/binding/c/mansrc/cart_sub.txt \
    src/binding/c/mansrc/cartdim_get.txt \
    src/binding/c/mansrc/dims_create.txt \
    src/binding/c/mansrc/dist_graph_create.txt \
    src/binding/c/mansrc/dist_graph_create_adjacent.txt \
    src/binding/c/mansrc/dist_graph_neighbors.txt \
    src/binding/c/mansrc/dist_graph_neighbors_count.txt \
    src/binding/c/mansrc/graph_create.txt \
    src/binding/c/mansrc/graph_get.txt \
    src/binding/c/mansrc/graph_map.txt \
    src/binding/c/mansrc/graph_neighbors.txt \
    src/binding/c/mansrc/graph_neighbors_count.txt \
    src/binding/c/mansrc/graphdims_get.txt \
    src/binding/c/mansrc/topo_test.txt
