dataDir: ./data/adult
dataset: adult
device: cpu
download: true
epochs: 20
log_step: 20
lr: 0.01
max_rank: 2
partition_method: vertical
variants_type: vertical
server_rank: 0
data_vertical_list: [6, 4, 4]
cut_layer_vertical_list: [4, 3, 3]


