# dataDir: ./data/
# #dataset: ["mnist", "fashionmnist"]
# #dataset: ["german", "german"]
# dataset: cifar10
# device: gpu
# gpu_num_per_server: 1
# download: true
# batch_size: 200
# epochs: 25
# log_step: 20
# lr: 0.01
# max_rank: 2
# partition_method: homo
# variants_type: vanilla
# #variants_type: psl
# #variants_type: Ushaped



# seed: 0
# partition_alpha: 2
# server_rank: 0
# model: LeNet
# split_layer: 1
# thred: 0.10

# partition_method_attributes: 7
# class_number_per_client: 4

# client_split: [3,5]
# data_vertical_list: [6, 4, 4]
# cut_layer_vertical_list: [4, 3, 3]
# SGLR_splitAvg_active: 0.5
# SGLR_splitLR: True
# SGLR_splitLR_alpha: 0.5
# #log_save_path: D:\Split-learning-Attacks\SABuf\Split-learning-Attacks\SLFrame\log.txt


# save_acts_step: 0
# save_attack_acts_step: 0
# save_model_epoch: 50

# ### Added
# # In config.yaml

# save_dirs:
#   - "./model_save/attack_acts/PSL/cifar10"
#   - "./logs"
#   - "./results"




# # dataDir: ./data/
# # dataset: cifar10
# # device: gpu
# # gpu_num_per_server: 1
# # download: true
# # batch_size: 64
# # epochs: 23
# # log_step: 10
# # lr: 0.01
# # max_rank: 2
# # partition_method: homo
# # variants_type: vanilla   # Use "vanilla" for a complete vanilla split learning model

# # seed: 0
# # partition_alpha: 2
# # server_rank: 0
# # model: LeNet
# # split_layer: 1
# # thred: 0.10

# # partition_method_attributes: 7
# # class_number_per_client: 4

# # client_split: [1]        # One client; with the server this makes 2 processes

# # # The following parameters are specific to vertical-splitting or SGLR variants
# # # and are not used for a complete vanilla model. They have been commented out.
# # # data_vertical_list: [6, 4, 4]
# # # cut_layer_vertical_list: [4, 3, 3]
# # # SGLR_splitAvg_active: 0.5
# # # SGLR_splitLR: True
# # # SGLR_splitLR_alpha: 0.5

# # save_acts_step: 0
# # save_attack_acts_step: 0
# # save_model_epoch: 50

# # save_dirs:
# #   - "./model_save/attack_acts/PSL/cifar10"
# #   - "./logs"
# #   - "./results"












# ################## ################## ################## 
# ################## Ushaped setup NON-IID


# # General settings
# dataDir: ./data/
# dataset: cifar10
# device: gpu
# gpu_num_per_server: 1
# download: true
# batch_size: 64
# epochs: 75
# lr: 0.01
# max_rank: 3  # 3 clients total

# # Non-IID Partitioning: Dirichlet
# partition_method: hetero  # Enables Non-IID partitioning
# partition_alpha: 0.001  # Dirichlet distribution parameter (0.1 = highly skewed, 10 = nearly IID)



# # Split Learning settings
# variants_type: Ushaped
# server_rank: 0
# # model: DenseNet  # Can be changed to LeNet\
# model: ResNet56
# split_layer: 1  # Layer at which model is split
# seed: 10  # For reproducibility

# # # Client data distribution
# # client_split: [1, 1, 1]  # Equal number of samples per client
# # save_model_epoch: 50

# # ### Added
# # # In config.yaml

# # save_dirs:
# #   - "./model_save/attack_acts/PSL/cifar10"
# #   - "./logs"
# #   - "./results"
# ################## ################## ################## 



# ################## Ushaped setup IID


# dataDir: ./data/
# dataset: cifar10
# device: gpu
# gpu_num_per_server: 1
# download: true
# batch_size: 64  # Paper’s value; yours is 200
# epochs: 75
# log_step: 10
# lr: 0.01
# max_rank: 2
# partition_method: homo
# # partition_method: hetero
# variants_type: Ushaped
# server_rank: 0
# model: DenseNet  # Paper uses ResNet56 for CIFAR-10, but your config aligns with models.py
# split_layer: 1
# seed: 0

# ################# 









################## ################## ################## 
# ################## ################## ################## 
# ################## SplitFed2 setup IID


# dataDir: ./data/
# dataset: cifar10
# device: gpu
# gpu_num_per_server: 1
# download: true
# batch_size: 64  # Paper’s value; yours is 200
# epochs: 75
# log_step: 10
# lr: 0.01
# max_rank: 2
# partition_method: homo
# # partition_method: hetero
# variants_type: SplitFed2
# server_rank: 0
# model: ResNet56  # Paper uses ResNet56 for CIFAR-10, but your config aligns with models.py
# split_layer: 1
# seed: 0

# ################# 

# ################## SplitFed NON-IID


# # General settings
# dataDir: ./data/
# dataset: cifar10
# device: gpu
# gpu_num_per_server: 1
# download: true
# batch_size: 64
# epochs: 75
# lr: 0.01
# max_rank: 3  # 3 clients total

# # Non-IID Partitioning: Dirichlet
# partition_method: hetero  # Enables Non-IID partitioning
# partition_alpha: 0.03  # Dirichlet distribution parameter (0.1 = highly skewed, 10 = nearly IID)



# # Split Learning settings
# variants_type: parallel_U_Shape
# server_rank: 0
# # model: DenseNet  # Can be changed to LeNet\
# model: ResNet56
# split_layer: 1  # Layer at which model is split
# seed: 10  # For reproducibility

# # # Client data distribution
# # client_split: [1, 1, 1]  # Equal number of samples per client
# # save_model_epoch: 50

# # ### Added
# # # In config.yaml

# # save_dirs:
# #   - "./model_save/attack_acts/PSL/cifar10"
# #   - "./logs"
# #   - "./results"
# ################## ################## ################## 

















#IID Steup
# # ################## Vanilla setup IID
# dataDir: ./data/
# dataset: cifar10
# device: gpu
# gpu_num_per_server: 1
# download: true
# batch_size: 32
# epochs: 100
# log_step: 30
# lr: 0.01
# max_rank: 2
# partition_method: homo
# variants_type: vanilla  
# server_rank: 0
# model: ResNet56 
# split_layer: 1
# seed: 0
# save_model_epoch: 50

# # # ################## Vanilla setup IID - MINST
# dataDir: ./data/
# dataset: mnist
# device: gpu
# gpu_num_per_server: 1
# download: true
# batch_size: 32
# epochs: 100
# log_step: 30
# lr: 0.01
# max_rank: 2
# partition_method: homo
# variants_type: vanilla 
# partition_alpha: 9999999999
# server_rank: 0
# model: ResNet56 
# split_layer: 1
# seed: 0
# save_model_epoch: 50




###### .PSL setup IID
# # ################## Vanilla setup IID
# dataDir: ./data/
# dataset: cifar10
# device: gpu
# gpu_num_per_server: 1
# download: true
# batch_size: 32
# epochs: 100
# log_step: 30
# lr: 0.01
# max_rank: 2
# partition_method: homo
# variants_type: VanillaPSL  
# partition_alpha: 1
# server_rank: 0
# model: ResNet56 
# split_layer: 1
# seed: 0
# save_model_epoch: 50


#######################







#Non-IID setup
# ################## ################## ##################


# ################## Vanilla setup NON-IID MINST
dataDir: ./data/
dataset: cifar10
device: gpu
gpu_num_per_server: 1
download: true
batch_size: 32
epochs: 100
log_step: 50
lr: 0.01
max_rank: 2
partition_method: base_on_class
variants_type: SplitFed
partition_alpha: 0.3
server_rank: 0
model: ResNet110
split_layer: 1
seed: 0


# ################## Vanilla setup NON-IID
# # General settings
# dataDir: ./data/
# dataset: cifar10
# device: gpu
# gpu_num_per_server: 1
# download: true
# batch_size: 32
# epochs: 100
# log_step: 30
# lr: 0.01
# max_rank: 2
# partition_method: base_on_class
# variants_type: vanilla   
# partition_alpha: 0
# seed: 0
# server_rank: 0
# model: ResNet56
# split_layer: 1
# thred: 0.10

# partition_method_attributes: 7
# class_number_per_client: 4

# client_split: [1]  


# ################## SplitFed2 setup NON-IID
# General settings
# ################## SplitFed setup Non-IID


#dataDir: ./data/
#dataset: cifar10
#device: gpu
#gpu_num_per_server: 1
#download: true
#partition_method: base_on_class
#partition_alpha: 0.3
#variants_type: SplitFed
#lr: 0.01
#max_rank: 2
#partition_method: base_on_class
#batch_size: 32
#epochs: 300
#log_step: 10
#server_rank: 0
#model: ResNet56 
#split_layer: 1
#seed: 0
#save_model_epoch: 50


################# 

###### .PSL setup IID

# dataDir: ./data/
# dataset: cifar10
# device: gpu
# gpu_num_per_server: 1
# download: true
# batch_size: 32
# epochs: 100
# log_step: 30
# lr: 0.01
# max_rank: 2
# partition_method: base_on_class
# variants_type: Asynchronous
# partition_alpha: 0
# server_rank: 0
# model: ResNet56 
# split_layer: 1
# seed: 0
# save_model_epoch: 50


###### uSHAPED setup NON-IID

#dataDir: ./data/
#dataset: cifar10
#device: gpu
#gpu_num_per_server: 1
#download: true
#batch_size: 32
#epochs: 100
#log_step: 30
#lr: 0.01
#max_rank: 2
#partition_method: base_on_class
#variants_type: parallel_U_Shape
#partition_alpha: 0
#server_rank: 0
#model: ResNet56 
#split_layer: 1
#seed: 0
#save_model_epoch: 50